# Generated by Django 5.0.6 on 2024-06-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Company_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Address', models.TextField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Description', models.TextField(null=True)),
                ('hsn_code', models.CharField(max_length=50)),
                ('Category', models.CharField(choices=[('Pesticide', 'Pesticide'), ('Fungicide', 'Fungicide'), ('Fertilizer', 'Fertilizer'), ('Herbicide', 'Herbicide'), ('Seeds', 'Seeds'), ('Bio', 'Bio')], default='Pesticide', max_length=50)),
                ('Manufacturer', models.CharField(max_length=250)),
                ('Formula', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='symptom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('disease_type', models.CharField(choices=[('Pest', 'Pest'), ('Fungi', 'Fungi'), ('Nematodes', 'Nematodes'), ('Bacteria', 'Bacteria')], default='Pest', max_length=15)),
                ('low_sev_formula', models.CharField(max_length=250)),
                ('low_sev_quant', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low_sev_unit', models.CharField(choices=[('Kg', 'Kg'), ('Grms', 'Grms'), ('Lts', 'Lts'), ('Mls', 'Mls')], default='Grms', max_length=25)),
                ('med_sev_formula', models.CharField(max_length=250)),
                ('med_sev_quant', models.DecimalField(decimal_places=3, max_digits=10)),
                ('med_sev_unit', models.CharField(choices=[('Kg', 'Kg'), ('Grms', 'Grms'), ('Lts', 'Lts'), ('Mls', 'Mls')], default='Grms', max_length=25)),
                ('high_sev_formula', models.CharField(max_length=250)),
                ('high_sev_quant', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high_sev_unit', models.CharField(choices=[('Kg', 'Kg'), ('Grms', 'Grms'), ('Lts', 'Lts'), ('Mls', 'Mls')], default='Grms', max_length=25)),
            ],
            options={
                'db_table': 'symptom',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('ID', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Batch_code', models.CharField(max_length=25)),
                ('Packaging_Size', models.IntegerField()),
                ('Unit', models.CharField(choices=[('Kg', 'Kg'), ('Grms', 'Grms'), ('Lts', 'Lts'), ('Mls', 'Mls')], default='Kg', max_length=25)),
                ('MRP', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Cost_Price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('CGST', models.DecimalField(decimal_places=3, max_digits=10)),
                ('SGST', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Profit_percentage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Selling_Price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product', verbose_name='Product')),
            ],
            options={
                'db_table': 'price',
            },
        ),
    ]
