# Generated by Django 5.0.6 on 2024-08-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi_product_info',
            name='price',
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Combo_Id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_info', to='website.price'),
        ),
    ]
