# Generated by Django 5.0.6 on 2024-06-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Invoice_Id', models.CharField(max_length=255)),
                ('Combo_Pk_Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Invoice_Date', models.DateField()),
                ('Company_Name', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Product_Name', models.CharField(max_length=255)),
                ('Batch_No', models.CharField(max_length=50)),
                ('Size', models.IntegerField()),
                ('Unit', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('BT_Rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('BT_Final_Amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=2)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=2)),
                ('PU_Final_Amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Combo_Id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'purchase_invoice',
            },
        ),
    ]
