# Generated by Django 5.0.6 on 2024-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_pi_product_info_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ri_invoice_info',
            name='Editable',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
