# Generated by Django 5.0.6 on 2024-06-16 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_purchase_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Product_Name', models.CharField(max_length=255)),
                ('Batch_No', models.CharField(max_length=50)),
                ('Size', models.IntegerField()),
                ('Unit', models.CharField(max_length=25)),
                ('Quantity', models.IntegerField()),
                ('Manufacture_date', models.DateField(default=datetime.date(2024, 6, 16))),
                ('Expiry_date', models.DateField(default=datetime.date(2024, 6, 16))),
                ('Combo_Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='purchase_invoice',
            name='Expiry_date',
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
        migrations.AddField(
            model_name='purchase_invoice',
            name='Manufacture_date',
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
        migrations.AlterField(
            model_name='purchase_invoice',
            name='Unit',
            field=models.CharField(max_length=25),
        ),
    ]
