# Generated by Django 5.0.6 on 2024-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_inventory_purchase_invoice_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Manufacture_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase_invoice',
            name='Expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase_invoice',
            name='Manufacture_date',
            field=models.DateField(),
        ),
    ]
