# Generated by Django 5.0.6 on 2024-09-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sales_invoice_info_sales_price_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_product_info',
            name='Category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
