# Generated by Django 5.0.6 on 2024-06-24 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_inventory_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PI_Invoice_info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Invoice_Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Invoice_Date', models.DateField()),
                ('Company_Name', models.CharField(max_length=255)),
                ('Address', models.TextField()),
            ],
            options={
                'db_table': 'PI_Invoice_info',
            },
        ),
        migrations.CreateModel(
            name='PI_Product_info',
            fields=[
                ('Id', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=255)),
                ('Batch_No', models.CharField(max_length=50)),
                ('Manufacture_date', models.DateField()),
                ('Expiry_date', models.DateField()),
                ('Size', models.IntegerField()),
                ('Unit', models.CharField(max_length=25)),
                ('Quantity', models.IntegerField()),
                ('BT_Rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('BT_Final_Amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=2)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=2)),
                ('PU_Final_Amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Combo_Pk_Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Combo_Id', models.CharField(max_length=255)),
                ('Invoice_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pi_invoice_info', verbose_name='Invoice_id')),
            ],
            options={
                'db_table': 'PI_Product_info',
            },
        ),
        migrations.DeleteModel(
            name='purchase_invoice',
        ),
    ]
