# Generated by Django 5.0.6 on 2024-09-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sales_product_info_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
