# Generated by Django 5.0.6 on 2024-07-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_pi_invoice_info_pi_product_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi_product_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='BT_Final_Amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='BT_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='CGST',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='PU_Final_Amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='SGST',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.CreateModel(
            name='PI_Purchase_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Final_Amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Additions', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Deductions', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Revised_Amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Comments', models.TextField()),
                ('Invoice_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pi_invoice_info', verbose_name='Invoice_id')),
            ],
            options={
                'db_table': 'PI_Purchase_Price',
            },
        ),
    ]
