# Generated by Django 5.0.6 on 2024-08-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_pi_product_info_combo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RI_Invoice_Info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Return_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Return_Date', models.DateField()),
                ('To_Company_Name', models.CharField(max_length=255)),
                ('To_Address', models.TextField()),
                ('From_Company_Name', models.CharField(max_length=255)),
                ('From_Address', models.TextField()),
            ],
            options={
                'db_table': 'RI_Invoice_Info',
            },
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='BT_Final_Amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='BT_Rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Batch_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='CGST',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Invoice_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pi_invoice_info', verbose_name='Invoice_id'),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='PU_Final_Amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Product_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='SGST',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi_product_info',
            name='Unit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='RI_Price_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Final_Amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Additions', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Deductions', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Revised_Amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Comments', models.TextField()),
                ('Return_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ri_invoice_info', verbose_name='Return_Id')),
            ],
            options={
                'db_table': 'RI_Price_Info',
            },
        ),
        migrations.CreateModel(
            name='RI_Product_Info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Id', models.IntegerField()),
                ('Product_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Batch_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Manufacture_date', models.DateField(blank=True, null=True)),
                ('Expiry_date', models.DateField(blank=True, null=True)),
                ('Size', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, max_length=25, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('BT_Rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('BT_Final_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('CGST', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('SGST', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('PU_Final_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Combo_Pk_Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Return_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ri_invoice_info', verbose_name='Return_Id')),
            ],
            options={
                'db_table': 'RI_Product_info',
            },
        ),
    ]
