# Generated by Django 5.0.6 on 2024-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_sales_product_info_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_price_info',
            name='Additions',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales_price_info',
            name='Aggregate_Sale_Amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales_price_info',
            name='Deductions',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales_price_info',
            name='Revised_Amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales_product_info',
            name='Retail_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales_product_info',
            name='Total_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='sales_invoice_info',
            table='Sale_Invoice_Info',
        ),
    ]
