# Generated by Django 5.0.6 on 2024-08-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_pi_product_info_combo_id_ri_product_info_combo_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
    ]
