# Generated by Django 5.0.6 on 2024-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_sales_invoice_info_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice_info',
            name='Expected_Payment_Date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_invoice_info',
            name='Payment_Type',
            field=models.CharField(default='Cash', max_length=5),
        ),
    ]
