# Generated by Django 5.0.6 on 2024-10-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_sales_invoice_info_expected_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice_info',
            name='Payment_Type',
            field=models.CharField(default='Cash', max_length=6),
        ),
    ]
