# Generated by Django 5.0.6 on 2024-10-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_sales_invoice_info_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_price_info',
            name='Due_Payment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales_price_info',
            name='Partial_Payment',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
