# Generated by Django 5.0.6 on 2024-11-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_sales_price_info_due_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Return_Invoice_Info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Sale_Return_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sale_Return_Date', models.DateField()),
                ('Customer_Name', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Mobile_No', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=255)),
                ('Editable', models.CharField(default=0, max_length=1)),
            ],
            options={
                'db_table': 'Sale_Return_Invoice_Info',
            },
        ),
        migrations.AlterField(
            model_name='sales_price_info',
            name='Due_Payment',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Sales_Return_Price_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Aggregate_Sale_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Additions', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Deductions', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Revised_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Comments', models.TextField()),
                ('Sale_Return_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sales_return_invoice_info', verbose_name='Sale_Id')),
            ],
            options={
                'db_table': 'Sale_Return_Price_Info',
            },
        ),
        migrations.CreateModel(
            name='Sales_Return_Product_Info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Id', models.IntegerField()),
                ('Company_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Batch_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Manufacture_date', models.DateField(blank=True, null=True)),
                ('Expiry_date', models.DateField(blank=True, null=True)),
                ('Size', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, max_length=25, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Retail_Price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Total_Price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Combo_Pk_Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Combo_Id', models.CharField(max_length=255)),
                ('Sale_Return_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sales_return_invoice_info', verbose_name='Sale_Id')),
            ],
            options={
                'db_table': 'Sale_Return_Product_info',
            },
        ),
    ]
