# Generated by Django 5.0.6 on 2025-03-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_sales_return_invoice_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_return_price_info',
            old_name='Aggregate_Sale_Amount',
            new_name='Aggregate_Return_Amount',
        ),
    ]
