# Generated by Django 5.0.6 on 2025-03-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_aggregate_sale_amount_sales_return_price_info_aggregate_return_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_return_product_info',
            old_name='Quantity',
            new_name='Purchased_Quantity',
        ),
        migrations.RenameField(
            model_name='sales_return_product_info',
            old_name='Retail_Price',
            new_name='Total_Retail_price',
        ),
        migrations.RemoveField(
            model_name='sales_return_product_info',
            name='Expiry_date',
        ),
        migrations.RemoveField(
            model_name='sales_return_product_info',
            name='Manufacture_date',
        ),
        migrations.RemoveField(
            model_name='sales_return_product_info',
            name='Total_Price',
        ),
        migrations.AddField(
            model_name='sales_return_product_info',
            name='Returned_Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales_return_product_info',
            name='Sale_Id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
